apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom
  template:
    metadata:
      labels:
        app: prom
    spec:
      containers:
        - name: prom
          image: prom/prometheus:v2.46.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          args:
            - "--config.file=/prometheus/prometheus.yml"
            - "--web.enable-remote-write-receiver"
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /prometheus    # æŒ‚ prometheus é…ç½®
              readOnly: true
            - name: alert-rules-config-volume
              mountPath: /etc/prometheus  # æŒ‚ alert è§„åˆ™
              readOnly: true
            - name: prometheus-data
              mountPath: /prometheus/data  # ğŸ”¥ æŒ‚è½½ data ç›®å½•
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config
        - name: alert-rules-config-volume
          configMap:
            name: alert-rules-config
        - name: prometheus-data
          emptyDir: { }   # ğŸ§¹ ä¸´æ—¶çš„ç©ºç›®å½•ï¼ŒPodé”€æ¯æ—¶ä¹Ÿä¸€èµ·æ¸…ç©º

